### ISSUE TITLE
WP1.5.1.5 Attendance of Community Engagement Team discussion series

### ISSUE THREAD

**Issue by bobmann** [lsst-uk/External-Liaison#16]
The Rubin Community Engagement Team is running a series of discussion meetings to influence their planning. This will be of relevance to our hosting of a DAC and running a Community Broker, so we should engage with this process. The CET will produce a summary report, but relevant team members should attend one of the discussion series, if possible, given their timing.

**Comment by MikeeRead** [comment]
Attended discussion 2020-11-19.

**Comment by tms-epcc** [comment]
Attended discussion 2020-11-19.

**Comment by tms-epcc** [comment]
01/OCT/21
- Bob and George also attended some.
- Bob agreed to close the ticket
